### ISSUE TITLE
Tuning parameter as field?

### ISSUE THREAD

**Issue by joshday** [JuliaML/PenaltyFunctions.jl#1]
I'm going back and forth over which of these works better for JuliaML.

``` julia
# version 1
immutable L1Penalty <: Penalty end
value{T<:Number}(p::L1Penalty, λ::T, x::T) = λ * abs(x)
```

``` julia
# version 2
immutable L1Penalty{T<:Number} <: Penalty 
    λ::T 
end
value{T<:Number}(p::L1Penalty{T}, x::T) = p.λ * abs(x)
```
- I would consider λ to be a learnable parameter, so I don't like the thought that it would be necessary to create many objective functions to calculate a solution path.  If we use version 2, should concrete penalties be a `type` vs. `immutable`?  
- Some penalties also include scaling the tuning parameter (adaptive LASSO) or you may not want to penalize known good predictors, which version 1 makes easier.
- A barebones version 2 is currently implemented, but I'm curious about what others think/foresee as problems with either version.

Just realized nobody is watching the repo by default...pings: @ahwillia @tbreloff @Evizero

**Comment by Evizero** [comment]
> I would consider λ to be a learnable parameter

Interesting, I have only really known it as a hyper parameter. If that is a use-case than that does change things a bit, yes.

For version 1. Would all penalties share the same interface, or would the signature depend on the penalty?

**Comment by tbreloff** [comment]
Is it "learnable"? Or "settable"?  The distinction is subtle but might change things.

I lean towards the second, with `type`.  If an algorithm chooses to do `p.λ = ...` that's their business and doesn't change much else.

This decision is similar to adaptive learning rates that I was looking at earlier.  We should probably do the same thing for both.

**Comment by joshday** [comment]
Hmm, It is a hyper parameter, but it's typically chosen (learned) through cross-validation.  I guess that's an extension to objective function, but not quite an objective function itself.  

For version 1, penalties would share the interface.  My thought was `value`/`prox`/`deriv` would all have a `function(p::MyPenalty, lambda::T, x::T)` interface.

**Comment by Evizero** [comment]
> but it's typically chosen (learned) through cross-validation.

Fair enough, but in that case type construction is negligible. It is much more expensive to compute any validation metric.

> For version 1, penalties would share the interface.

My main worry is that we would need to propagate lambda in a lot of unfortunate places, such as where structural risks end up.
We would also still need the dummy lambda if we are using no penalty at all.

**Comment by joshday** [comment]
@tbreloff could you point me to any discussion/code?

**Comment by tbreloff** [comment]
Nothing pushed yet... just me working on StochasticOptimization.  Here's a prototype that doesn't work:

``` julia
export
    AbstractLearningRate,
    FixedLR,
    AdaptiveLR

"Enacts a strategy to adjust the learning rate"
abstract AbstractLearningRate

@with_kw immutable FixedLR <: AbstractLearningRate
    lr::Float64 = 1e-2
end
update!(lr::FixedLR, err) = lr


"Adapts learning rate based on relative variance of the changes in the test error"
@with_kw type AdaptiveLR <: AbstractLearningRate
    lr::Float64 = 1e-2
    ε::Diff{Float64} = Diff()
    lookback::Int = 20
    σ²::Variance{BoundedEqualWeight} = Variance(BoundedEqualWeight(lookback))
    adjpct::Float64 = 1e-2
    cutoff::Float64 = 1e-1
end


# if the error is decreasing at a large rate relative to the variance, increase the learning rate (speed it up)
function update!(lr::AdaptiveLR, err)
    fit!(lr.ε, err)
    fit!(lr.σ², diff(lr.ε))
    μ = mean(lr.σ²)
    σ = std(lr.σ²)
    if σ > 0
        pct = lr.adjpct * (μ / σ < -lr.cutoff ? 1.0 : -1.0)
        lr.lr *= (1.0 + pct)
    end
    lr
end
```

**Comment by joshday** [comment]
> We would also still need the dummy lambda if we are using no penalty at all.

That is an ugly consequence that would be nice to avoid.

> I lean towards the second, with type

I agree.  I'll give it another go with type.
