### ISSUE TITLE
SCAD penalty and its lambda

### ISSUE THREAD

**Issue by Evizero** [JuliaML/PenaltyFunctions.jl#12]
From all the element-wise penalties the SCAD one stands out because it break interface somewhat. Mainly because one must specify `lamda` for the SCAD one while for the others it is optional. Furthermore, given the signature this `lamda` is treated as the SCAD version of a scaling factor 

I'd like to argue that the `lambda` for SCAD and the generic scaling factor that is usually used to weight the influence of the penalty on the structural risk are two distinct entities. More specifically I think it is relevant to allow for a generic way to really compute a weighted sum of loss and penalty, which this lambda is not doing. 

I'd like to suggest to make the lambda of SCAD (described in the presentation you linked in the code) into a second member variable of SCAD instead, and thus treat it distinct from the weighted sum factor.

This is also relevant for the points raised in #10

**Comment by joshday** [comment]
I was still trying to figure out the best solution for SCAD.  I like this idea.

**Comment by Evizero** [comment]
I'll give it a shot

**Comment by Evizero** [comment]
closed by #16
