### ISSUE TITLE
p vs ρ

### ISSUE THREAD

**Issue by Evizero** [JuliaML/PenaltyFunctions.jl#2]
This is only a small nitpick, but while browsing through your code I had to double check a couple of times if I am reading `p` or `ρ`. Can we maybe consider a more distinct variable?

https://github.com/JuliaML/Penalties.jl/blob/master/src/elementwise.jl#L12-L19

**Comment by Evizero** [comment]
I do understand that it can be inferred quite easily by how the variable is used, but it still seems like something that could lead to confusing errors during maintenance or expansion of the package

**Comment by joshday** [comment]
That's a valid point, and an easy change.  I'll fix it.
