### ISSUE TITLE
Tests failing on PkgEvaluator

### ISSUE THREAD

**Issue by Evizero** [JuliaML/PenaltyFunctions.jl#25]
Some rounding error it seems

http://pkg.julialang.org/logs/PenaltyFunctions_0.6.log

**Comment by joshday** [comment]
That's strange.  Can you reproduce on your machine?  I cannot.

**Comment by Evizero** [comment]
I have not tried. I just saw the red badge while going over open issues in our repositories. I guess this could have an easy bandage by just rounding more aggressively.
