### ISSUE TITLE
Drop 0.4?

### ISSUE THREAD

**Issue by joshday** [JuliaML/PenaltyFunctions.jl#3]
Supporting both 0.4 and 0.5 has its headaches.  Any thoughts on how dedicated we should be to supporting both?  

I would prefer to only support 0.5, but Penalties should match what Losses supports.

**Comment by Evizero** [comment]
Related: https://github.com/JuliaML/Losses.jl/issues/15#issuecomment-241654881

tl;dr I have not switched to 0.5 yet, but I can get behind 0.5+ going forward

**Comment by joshday** [comment]
Cool.  I'll go ahead and focus on 0.5.
