### ISSUE TITLE
get rid of value

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/PenaltyFunctions.jl#34]
Maybe this has already been discussed at some point, but I wonder why this package has a  ` value` method 
```julia 
p = L1Penalty()
x = 1  
value(p, x)    
```
instead of the simpler interface
```julia 
p(x)
```
?

**Comment by joshday** [comment]
I don't think we'd want to remove `value`, but making penalties callable is easy.  Fixed on master (which requires Julia 0.7).

**Comment by CarloLucibello** [comment]
Nice, thank you! Add tests/readme?

**Comment by joshday** [comment]
Added.  Plus a pending new release.
