### ISSUE TITLE
shift to project.toml?

### ISSUE THREAD

**Issue by mkborregaard** [JuliaML/PenaltyFunctions.jl#38]
Hi this package is causing some dependency issues downstream (Diversity.jl) when trying to shift to a project.toml based dependency. Would make sense to update?

**Comment by asinghvi17** [comment]
This is also holding back RecipesBase 1.0.

**Comment by mkborregaard** [comment]
I've got a PR fixing this here https://github.com/JuliaML/PenaltyFunctions.jl/pull/39
