### ISSUE TITLE
Get this ready for metadata or merge with LossFunctions?

### ISSUE THREAD

**Issue by joshday** [JuliaML/PenaltyFunctions.jl#7]
I'm starting to lean toward merging this with LossFunctions as opposed to renaming as PenaltyFunctions (or another metadata-acceptable name).  I'd like to get some thoughts from you all.

**Comment by Evizero** [comment]
Unless there is some kind of code synergy that comes with merging I would rather have them in separate packages. Otherwise LossFunctions becomes a collection of two disjoint sub-modules more or less.

**Comment by tbreloff** [comment]
I'm indifferent. Happy to merge or not.

**Comment by joshday** [comment]
Fair enough, keeping them separate works for me.  I'd like to change the name to PenaltyFunctions this week unless I hear objection.

**Comment by Evizero** [comment]
`MLPenalties` is also quite nice. That said, I have no objections to `PenaltyFunctions` either

**Comment by Evizero** [comment]
Hey @joshday . I'd like to help get this package ready over new years. Here are some thoughts on what needs to be done, which I'll happily volunteer for.

- [x] ~~Basic readthedocs documentation in JuliaML Style~
- [x] Test type stability and flexibility
- [x] broadcast support, which will make `grad` (and especially `grad!`) nicer
- [x] Format readme into a JuliaML like style

Anything else you can think of?

**Comment by Evizero** [comment]
would maybe be nice to plot the penality structure for 2d parameter vectors, such as Hastie and tibshirani and friedman do in elemstatlearn page 71 and 73

**Comment by joshday** [comment]
That's sounds great @Evizero!  Feel free to start making these changes and let me know what you want help with!

**Comment by joshday** [comment]
When you say "Format readme into a JuliaML like style", is that basically using the LossFunctions readme as a template?  I can work on that.

**Comment by Evizero** [comment]
yes, something like that!

**Comment by Evizero** [comment]
Sorry for the delay. As usual I am taking longer to do things as my mouth does to make promises. I want to focus on PenaltyFunction right after the new LossFunction changes (which will probably include some documentation additions).

**Comment by Evizero** [comment]
Just a follow up on my post. I think at this point a read-the-docs documentation would be a bit overkill and not really needed to get this package on the road. I will instead focus on the readme a bit

**Comment by Ayush-iitkgp** [comment]
Hi,
We are planning to use this package as the dependency in our work. It would be great if it could be registered in METADATA in near days.

**Comment by Evizero** [comment]
I think it is pretty much ready except a few little details I'd like to double check. I'll register it before the end of this week unless the main author @joshday objects.

**Comment by Evizero** [comment]
I think the package is ready for the initial release. I don't quite know if METADATA will accept `julia 0.6-` minimum requirements yet, but doesn't hurt to try I suppose. 

@joshday would you do the honours of [creating the first release](https://github.com/JuliaML/PenaltyFunctions.jl/releases)? Attobot looks activated

**Comment by Ayush-iitkgp** [comment]
Pkg.add("PenaltyFunctions") is still throwing ERROR: unknown package PenaltyFunctions.

**Comment by Evizero** [comment]
registering packages takes a few days: https://github.com/JuliaLang/METADATA.jl/pull/8575
