### ISSUE TITLE
doc images

### ISSUE THREAD

**Issue by joshday** [JuliaML/PenaltyFunctions.jl#8]
![readmefig](https://cloud.githubusercontent.com/assets/8075494/20890409/c778e6f2-bad4-11e6-9485-6886b84b741e.png)

**Comment by Evizero** [comment]
That is also cool

**Comment by Evizero** [comment]
maybe something like this next to it:

![plt](http://scikit-learn.org/stable/_images/sphx_glr_plot_sgd_penalties_0011.png)

(This particular image is from scikit learn)

**Comment by joshday** [comment]
Yes, that's exactly what I was thinking!

**Comment by Evizero** [comment]
the colorscheme `:darktest` is quite nice. I host the LossFunction images in [JuliaML/FileStorage](https://github.com/JuliaML/FileStorage), feel free to do the same. Here is the script I used to produce all images https://github.com/JuliaML/FileStorage/blob/master/LossFunctions/createplots.jl

SVGs look really nice and clean. examples: http://lossesjl.readthedocs.io/en/latest/losses/distance.html

**Comment by joshday** [comment]
Thanks for the pointers!  I'll keep the images here for now until I finalize them so I don't bloat the FileStorage repo.

**Comment by joshday** [comment]
Ah...except I apparently can't save SVGs here.  I suppose that's why you made FileStorage in the first place.

**Comment by Evizero** [comment]
sure. there is no pressure. PNGs are perfectly fine. I can also take care of these things later when I get around to write some docs. which should be in about two weeks time

**Comment by Evizero** [comment]
I am making progress.

![index](https://cloud.githubusercontent.com/assets/10854026/22822470/f28cc040-ef7f-11e6-9be2-034489bea99f.png)

**Comment by joshday** [comment]
![readmefig](https://cloud.githubusercontent.com/assets/8075494/22839303/d5269fe6-ef96-11e6-8c27-29b52d5e4499.png)

**Comment by Evizero** [comment]
very nice. I am starting the process of generating and hosting plots as svg at the FileStorage repo.

**Comment by Evizero** [comment]
subsumed by what is happening over at https://github.com/JuliaML/FileStorage/tree/master/PenaltyFunctions . Changes will be visible once my changes to the readme are merged
